// Función reusable para ejecutar cualquier bloque dentro de Docker
def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()
    }
}

pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    stage('Build CI Image') {
      steps {
        // Construimos la imagen desde devops/ci.Dockerfile
        sh 'docker build -t devops/ci:latest -f devops/ci.Dockerfile .'
      }
    }
    stage('Lint') {
      steps {
        script {
          runInDocker('devops/ci:latest') {
            // Instalamos linters y dependencias extra
            sh '''
               pip install -r requirements.txt flake8 mypy black
               make reformat
               make lint
            '''
          }
        }
      }
    }
    stage('Test') {            
      steps {
        script {
          runInDocker('python:3.6-slim') {
            sh '''
                  pip install -r requirements.txt || true
                  pytest
            '''
          }
        }
      }
    }
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }
  }
}
